# Generated by Django 5.2.1 on 2026-05-05 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='confidence_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='detected_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='fallback_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reviewed_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='source',
            field=models.CharField(choices=[('rule_engine', 'Rule Engine'), ('ai_service', 'AI Service'), ('fallback', 'Fallback'), ('human', 'Human')], default='rule_engine', max_length=20),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='escalation_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_risk_level',
            field=models.CharField(default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('flagged', 'Flagged'), ('escalated', 'Escalated')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='moodcheckin',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mood_check_ins', to='chat.chatsession'),
        ),
        migrations.AddField(
            model_name='moodcheckin',
            name='stress_level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=20),
        ),
    ]
