services:
  - type: web
    name: mental-health-system
    runtime: python
    rootDir: mental_health_chatbot/backend

    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate

    startCommand: gunicorn config.wsgi:application

    envVars:
      - key: SECRET_KEY
        generateValue: true

      - key: DEBUG
        value: "False"

      - key: ALLOWED_HOSTS
        value: mental-health-system-fc5k.onrender.com

      - key: CSRF_TRUSTED_ORIGINS
        value: https://mental-health-system-fc5k.onrender.com

      - key: CORS_ALLOW_ALL_ORIGINS
        value: "False"

      - key: DB_ENGINE
        value: django.db.backends.postgresql

      - key: DB_NAME
        fromDatabase:
          name: mental-health-db
          property: database

      - key: DB_USER
        fromDatabase:
          name: mental-health-db
          property: user

      - key: DB_PASSWORD
        fromDatabase:
          name: mental-health-db
          property: password

      - key: DB_HOST
        fromDatabase:
          name: mental-health-db
          property: host

      - key: DB_PORT
        fromDatabase:
          name: mental-health-db
          property: port

      - key: GUEST_CHAT_TOKEN_LIMIT
        value: "2400"

      - key: LLM_PROVIDER
        value: openrouter

      - key: OPENROUTER_API_KEY
        sync: false

      - key: LLM_MODEL
        value: openrouter/free

databases:
  - name: mental-health-db
    databaseName: health
    user: mental_health_user
