# Generated by Django 5.2.1 on 2026-05-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('anxiety', 'Anxiety'), ('stress', 'Stress'), ('crisis', 'Crisis')], default='general', max_length=20)),
                ('is_emergency', models.BooleanField(default=False)),
            ],
        ),
    ]
