# Generated by Django 5.2.1 on 2026-05-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcerecommendation',
            name='audience',
            field=models.CharField(choices=[('all', 'All'), ('student', 'Student'), ('support', 'Support')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='resourcerecommendation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resourcerecommendation',
            name='priority',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='resourcerecommendation',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
