# Generated by Django 5.2.1 on 2026-05-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_consent_accepted_at_user_display_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auto_open_resources",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="save_chat_history",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="save_mood_checkins",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="simplified_help_mode",
            field=models.BooleanField(default=False),
        ),
    ]
